# Generated by Django 2.2.3 on 2019-07-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
    ]
